package magellan.plugin.statistics.torque;


import java.math.BigDecimal;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;

import org.apache.commons.lang.ObjectUtils;
import org.apache.torque.TorqueException;
import org.apache.torque.map.TableMap;
import org.apache.torque.om.BaseObject;
import org.apache.torque.om.ComboKey;
import org.apache.torque.om.DateKey;
import org.apache.torque.om.NumberKey;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.om.StringKey;
import org.apache.torque.om.Persistent;
import org.apache.torque.util.Criteria;
import org.apache.torque.util.Transaction;





/**
 * Contains informations about regions
 *
 * This class was autogenerated by Torque on:
 *
 * [Thu May 22 14:33:00 CEST 2008]
 *
 * You should not use this class directly.  It should not even be
 * extended all references should be to RegionStatistics
 */
public abstract class BaseRegionStatistics extends BaseObject
{
    /** Serial version */
    private static final long serialVersionUID = 1211459580847L;

    /** The Peer class */
    private static final RegionStatisticsPeer peer =
        new RegionStatisticsPeer();


    /** The value for the iD field */
    private long iD;

    /** The value for the reportId field */
    private long reportId;

    /** The value for the regionNumber field */
    private String regionNumber;


    /**
     * Get the ID
     *
     * @return long
     */
    public long getID()
    {
        return iD;
    }


    /**
     * Set the value of ID
     *
     * @param v new value
     */
    public void setID(long v) throws TorqueException
    {

        if (this.iD != v)
        {
            this.iD = v;
            setModified(true);
        }



        // update associated RegionStatisticsData
        if (collRegionStatisticsDatas != null)
        {
            for (int i = 0; i < collRegionStatisticsDatas.size(); i++)
            {
                ((RegionStatisticsData) collRegionStatisticsDatas.get(i))
                        .setRegionId(v);
            }
        }

        // update associated RegionStatisticsPricesData
        if (collRegionStatisticsPricesDatas != null)
        {
            for (int i = 0; i < collRegionStatisticsPricesDatas.size(); i++)
            {
                ((RegionStatisticsPricesData) collRegionStatisticsPricesDatas.get(i))
                        .setRegionId(v);
            }
        }

        // update associated RegionStatisticsResourcesData
        if (collRegionStatisticsResourcesDatas != null)
        {
            for (int i = 0; i < collRegionStatisticsResourcesDatas.size(); i++)
            {
                ((RegionStatisticsResourcesData) collRegionStatisticsResourcesDatas.get(i))
                        .setRegionId(v);
            }
        }
    }

    /**
     * Get the ReportId
     *
     * @return long
     */
    public long getReportId()
    {
        return reportId;
    }


    /**
     * Set the value of ReportId
     *
     * @param v new value
     */
    public void setReportId(long v) throws TorqueException
    {

        if (this.reportId != v)
        {
            this.reportId = v;
            setModified(true);
        }


        if (aReport != null && !(aReport.getID() == v))
        {
            aReport = null;
        }

    }

    /**
     * Get the RegionNumber
     *
     * @return String
     */
    public String getRegionNumber()
    {
        return regionNumber;
    }


    /**
     * Set the value of RegionNumber
     *
     * @param v new value
     */
    public void setRegionNumber(String v) 
    {

        if (!ObjectUtils.equals(this.regionNumber, v))
        {
            this.regionNumber = v;
            setModified(true);
        }


    }

    



    private Report aReport;

    /**
     * Declares an association between this object and a Report object
     *
     * @param v Report
     * @throws TorqueException
     */
    public void setReport(Report v) throws TorqueException
    {
        if (v == null)
        {
            setReportId( 0);
        }
        else
        {
            setReportId(v.getID());
        }
        aReport = v;
    }


    /**
     * Returns the associated Report object.
     * If it was not retrieved before, the object is retrieved from
     * the database
     *
     * @return the associated Report object
     * @throws TorqueException
     */
    public Report getReport()
        throws TorqueException
    {
        if (aReport == null && (this.reportId != 0))
        {
            aReport = ReportPeer.retrieveByPK(SimpleKey.keyFor(this.reportId));
        }
        return aReport;
    }

    /**
     * Return the associated Report object
     * If it was not retrieved before, the object is retrieved from
     * the database using the passed connection
     *
     * @param connection the connection used to retrieve the associated object
     *        from the database, if it was not retrieved before
     * @return the associated Report object
     * @throws TorqueException
     */
    public Report getReport(Connection connection)
        throws TorqueException
    {
        if (aReport == null && (this.reportId != 0))
        {
            aReport = ReportPeer.retrieveByPK(SimpleKey.keyFor(this.reportId), connection);
        }
        return aReport;
    }

    /**
     * Provides convenient way to set a relationship based on a
     * ObjectKey, for example
     * <code>bar.setFooKey(foo.getPrimaryKey())</code>
     *
     */
    public void setReportKey(ObjectKey key) throws TorqueException
    {

        setReportId(((NumberKey) key).longValue());
    }
   


    /**
     * Collection to store aggregation of collRegionStatisticsDatas
     */
    protected List<RegionStatisticsData> collRegionStatisticsDatas;

    /**
     * Temporary storage of collRegionStatisticsDatas to save a possible db hit in
     * the event objects are add to the collection, but the
     * complete collection is never requested.
     */
    protected void initRegionStatisticsDatas()
    {
        if (collRegionStatisticsDatas == null)
        {
            collRegionStatisticsDatas = new ArrayList<RegionStatisticsData>();
        }
    }


    /**
     * Method called to associate a RegionStatisticsData object to this object
     * through the RegionStatisticsData foreign key attribute
     *
     * @param l RegionStatisticsData
     * @throws TorqueException
     */
    public void addRegionStatisticsData(RegionStatisticsData l) throws TorqueException
    {
        getRegionStatisticsDatas().add(l);
        l.setRegionStatistics((RegionStatistics) this);
    }

    /**
     * Method called to associate a RegionStatisticsData object to this object
     * through the RegionStatisticsData foreign key attribute using connection.
     *
     * @param l RegionStatisticsData
     * @throws TorqueException
     */
    public void addRegionStatisticsData(RegionStatisticsData l, Connection con) throws TorqueException
    {
        getRegionStatisticsDatas(con).add(l);
        l.setRegionStatistics((RegionStatistics) this);
    }

    /**
     * The criteria used to select the current contents of collRegionStatisticsDatas
     */
    private Criteria lastRegionStatisticsDatasCriteria = null;

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getRegionStatisticsDatas(new Criteria())
     *
     * @return the collection of associated objects
     * @throws TorqueException
     */
    public List<RegionStatisticsData> getRegionStatisticsDatas()
        throws TorqueException
    {
        if (collRegionStatisticsDatas == null)
        {
            collRegionStatisticsDatas = getRegionStatisticsDatas(new Criteria(10));
        }
        return collRegionStatisticsDatas;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this RegionStatistics has previously
     * been saved, it will retrieve related RegionStatisticsDatas from storage.
     * If this RegionStatistics is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     *
     * @throws TorqueException
     */
    public List<RegionStatisticsData> getRegionStatisticsDatas(Criteria criteria) throws TorqueException
    {
        if (collRegionStatisticsDatas == null)
        {
            if (isNew())
            {
               collRegionStatisticsDatas = new ArrayList<RegionStatisticsData>();
            }
            else
            {
                criteria.add(RegionStatisticsDataPeer.REGION_ID, getID() );
                collRegionStatisticsDatas = RegionStatisticsDataPeer.doSelect(criteria);
            }
        }
        else
        {
            // criteria has no effect for a new object
            if (!isNew())
            {
                // the following code is to determine if a new query is
                // called for.  If the criteria is the same as the last
                // one, just return the collection.
                criteria.add(RegionStatisticsDataPeer.REGION_ID, getID());
                if (!lastRegionStatisticsDatasCriteria.equals(criteria))
                {
                    collRegionStatisticsDatas = RegionStatisticsDataPeer.doSelect(criteria);
                }
            }
        }
        lastRegionStatisticsDatasCriteria = criteria;

        return collRegionStatisticsDatas;
    }

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getRegionStatisticsDatas(new Criteria(),Connection)
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List<RegionStatisticsData> getRegionStatisticsDatas(Connection con) throws TorqueException
    {
        if (collRegionStatisticsDatas == null)
        {
            collRegionStatisticsDatas = getRegionStatisticsDatas(new Criteria(10), con);
        }
        return collRegionStatisticsDatas;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this RegionStatistics has previously
     * been saved, it will retrieve related RegionStatisticsDatas from storage.
     * If this RegionStatistics is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List<RegionStatisticsData> getRegionStatisticsDatas(Criteria criteria, Connection con)
            throws TorqueException
    {
        if (collRegionStatisticsDatas == null)
        {
            if (isNew())
            {
               collRegionStatisticsDatas = new ArrayList<RegionStatisticsData>();
            }
            else
            {
                 criteria.add(RegionStatisticsDataPeer.REGION_ID, getID());
                 collRegionStatisticsDatas = RegionStatisticsDataPeer.doSelect(criteria, con);
             }
         }
         else
         {
             // criteria has no effect for a new object
             if (!isNew())
             {
                 // the following code is to determine if a new query is
                 // called for.  If the criteria is the same as the last
                 // one, just return the collection.
                 criteria.add(RegionStatisticsDataPeer.REGION_ID, getID());
                 if (!lastRegionStatisticsDatasCriteria.equals(criteria))
                 {
                     collRegionStatisticsDatas = RegionStatisticsDataPeer.doSelect(criteria, con);
                 }
             }
         }
         lastRegionStatisticsDatasCriteria = criteria;

         return collRegionStatisticsDatas;
     }











    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this RegionStatistics is new, it will return
     * an empty collection; or if this RegionStatistics has previously
     * been saved, it will retrieve related RegionStatisticsDatas from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in RegionStatistics.
     */
    protected List<RegionStatisticsData> getRegionStatisticsDatasJoinRegionStatistics(Criteria criteria)
        throws TorqueException
    {
        if (collRegionStatisticsDatas == null)
        {
            if (isNew())
            {
               collRegionStatisticsDatas = new ArrayList<RegionStatisticsData>();
            }
            else
            {
                criteria.add(RegionStatisticsDataPeer.REGION_ID, getID());
                collRegionStatisticsDatas = RegionStatisticsDataPeer.doSelectJoinRegionStatistics(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            criteria.add(RegionStatisticsDataPeer.REGION_ID, getID());
            if (!lastRegionStatisticsDatasCriteria.equals(criteria))
            {
                collRegionStatisticsDatas = RegionStatisticsDataPeer.doSelectJoinRegionStatistics(criteria);
            }
        }
        lastRegionStatisticsDatasCriteria = criteria;

        return collRegionStatisticsDatas;
    }





    /**
     * Collection to store aggregation of collRegionStatisticsPricesDatas
     */
    protected List<RegionStatisticsPricesData> collRegionStatisticsPricesDatas;

    /**
     * Temporary storage of collRegionStatisticsPricesDatas to save a possible db hit in
     * the event objects are add to the collection, but the
     * complete collection is never requested.
     */
    protected void initRegionStatisticsPricesDatas()
    {
        if (collRegionStatisticsPricesDatas == null)
        {
            collRegionStatisticsPricesDatas = new ArrayList<RegionStatisticsPricesData>();
        }
    }


    /**
     * Method called to associate a RegionStatisticsPricesData object to this object
     * through the RegionStatisticsPricesData foreign key attribute
     *
     * @param l RegionStatisticsPricesData
     * @throws TorqueException
     */
    public void addRegionStatisticsPricesData(RegionStatisticsPricesData l) throws TorqueException
    {
        getRegionStatisticsPricesDatas().add(l);
        l.setRegionStatistics((RegionStatistics) this);
    }

    /**
     * Method called to associate a RegionStatisticsPricesData object to this object
     * through the RegionStatisticsPricesData foreign key attribute using connection.
     *
     * @param l RegionStatisticsPricesData
     * @throws TorqueException
     */
    public void addRegionStatisticsPricesData(RegionStatisticsPricesData l, Connection con) throws TorqueException
    {
        getRegionStatisticsPricesDatas(con).add(l);
        l.setRegionStatistics((RegionStatistics) this);
    }

    /**
     * The criteria used to select the current contents of collRegionStatisticsPricesDatas
     */
    private Criteria lastRegionStatisticsPricesDatasCriteria = null;

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getRegionStatisticsPricesDatas(new Criteria())
     *
     * @return the collection of associated objects
     * @throws TorqueException
     */
    public List<RegionStatisticsPricesData> getRegionStatisticsPricesDatas()
        throws TorqueException
    {
        if (collRegionStatisticsPricesDatas == null)
        {
            collRegionStatisticsPricesDatas = getRegionStatisticsPricesDatas(new Criteria(10));
        }
        return collRegionStatisticsPricesDatas;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this RegionStatistics has previously
     * been saved, it will retrieve related RegionStatisticsPricesDatas from storage.
     * If this RegionStatistics is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     *
     * @throws TorqueException
     */
    public List<RegionStatisticsPricesData> getRegionStatisticsPricesDatas(Criteria criteria) throws TorqueException
    {
        if (collRegionStatisticsPricesDatas == null)
        {
            if (isNew())
            {
               collRegionStatisticsPricesDatas = new ArrayList<RegionStatisticsPricesData>();
            }
            else
            {
                criteria.add(RegionStatisticsPricesDataPeer.REGION_ID, getID() );
                collRegionStatisticsPricesDatas = RegionStatisticsPricesDataPeer.doSelect(criteria);
            }
        }
        else
        {
            // criteria has no effect for a new object
            if (!isNew())
            {
                // the following code is to determine if a new query is
                // called for.  If the criteria is the same as the last
                // one, just return the collection.
                criteria.add(RegionStatisticsPricesDataPeer.REGION_ID, getID());
                if (!lastRegionStatisticsPricesDatasCriteria.equals(criteria))
                {
                    collRegionStatisticsPricesDatas = RegionStatisticsPricesDataPeer.doSelect(criteria);
                }
            }
        }
        lastRegionStatisticsPricesDatasCriteria = criteria;

        return collRegionStatisticsPricesDatas;
    }

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getRegionStatisticsPricesDatas(new Criteria(),Connection)
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List<RegionStatisticsPricesData> getRegionStatisticsPricesDatas(Connection con) throws TorqueException
    {
        if (collRegionStatisticsPricesDatas == null)
        {
            collRegionStatisticsPricesDatas = getRegionStatisticsPricesDatas(new Criteria(10), con);
        }
        return collRegionStatisticsPricesDatas;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this RegionStatistics has previously
     * been saved, it will retrieve related RegionStatisticsPricesDatas from storage.
     * If this RegionStatistics is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List<RegionStatisticsPricesData> getRegionStatisticsPricesDatas(Criteria criteria, Connection con)
            throws TorqueException
    {
        if (collRegionStatisticsPricesDatas == null)
        {
            if (isNew())
            {
               collRegionStatisticsPricesDatas = new ArrayList<RegionStatisticsPricesData>();
            }
            else
            {
                 criteria.add(RegionStatisticsPricesDataPeer.REGION_ID, getID());
                 collRegionStatisticsPricesDatas = RegionStatisticsPricesDataPeer.doSelect(criteria, con);
             }
         }
         else
         {
             // criteria has no effect for a new object
             if (!isNew())
             {
                 // the following code is to determine if a new query is
                 // called for.  If the criteria is the same as the last
                 // one, just return the collection.
                 criteria.add(RegionStatisticsPricesDataPeer.REGION_ID, getID());
                 if (!lastRegionStatisticsPricesDatasCriteria.equals(criteria))
                 {
                     collRegionStatisticsPricesDatas = RegionStatisticsPricesDataPeer.doSelect(criteria, con);
                 }
             }
         }
         lastRegionStatisticsPricesDatasCriteria = criteria;

         return collRegionStatisticsPricesDatas;
     }











    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this RegionStatistics is new, it will return
     * an empty collection; or if this RegionStatistics has previously
     * been saved, it will retrieve related RegionStatisticsPricesDatas from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in RegionStatistics.
     */
    protected List<RegionStatisticsPricesData> getRegionStatisticsPricesDatasJoinRegionStatisticsData(Criteria criteria)
        throws TorqueException
    {
        if (collRegionStatisticsPricesDatas == null)
        {
            if (isNew())
            {
               collRegionStatisticsPricesDatas = new ArrayList<RegionStatisticsPricesData>();
            }
            else
            {
                criteria.add(RegionStatisticsPricesDataPeer.REGION_ID, getID());
                collRegionStatisticsPricesDatas = RegionStatisticsPricesDataPeer.doSelectJoinRegionStatisticsData(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            criteria.add(RegionStatisticsPricesDataPeer.REGION_ID, getID());
            if (!lastRegionStatisticsPricesDatasCriteria.equals(criteria))
            {
                collRegionStatisticsPricesDatas = RegionStatisticsPricesDataPeer.doSelectJoinRegionStatisticsData(criteria);
            }
        }
        lastRegionStatisticsPricesDatasCriteria = criteria;

        return collRegionStatisticsPricesDatas;
    }









    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this RegionStatistics is new, it will return
     * an empty collection; or if this RegionStatistics has previously
     * been saved, it will retrieve related RegionStatisticsPricesDatas from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in RegionStatistics.
     */
    protected List<RegionStatisticsPricesData> getRegionStatisticsPricesDatasJoinRegionStatistics(Criteria criteria)
        throws TorqueException
    {
        if (collRegionStatisticsPricesDatas == null)
        {
            if (isNew())
            {
               collRegionStatisticsPricesDatas = new ArrayList<RegionStatisticsPricesData>();
            }
            else
            {
                criteria.add(RegionStatisticsPricesDataPeer.REGION_ID, getID());
                collRegionStatisticsPricesDatas = RegionStatisticsPricesDataPeer.doSelectJoinRegionStatistics(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            criteria.add(RegionStatisticsPricesDataPeer.REGION_ID, getID());
            if (!lastRegionStatisticsPricesDatasCriteria.equals(criteria))
            {
                collRegionStatisticsPricesDatas = RegionStatisticsPricesDataPeer.doSelectJoinRegionStatistics(criteria);
            }
        }
        lastRegionStatisticsPricesDatasCriteria = criteria;

        return collRegionStatisticsPricesDatas;
    }





    /**
     * Collection to store aggregation of collRegionStatisticsResourcesDatas
     */
    protected List<RegionStatisticsResourcesData> collRegionStatisticsResourcesDatas;

    /**
     * Temporary storage of collRegionStatisticsResourcesDatas to save a possible db hit in
     * the event objects are add to the collection, but the
     * complete collection is never requested.
     */
    protected void initRegionStatisticsResourcesDatas()
    {
        if (collRegionStatisticsResourcesDatas == null)
        {
            collRegionStatisticsResourcesDatas = new ArrayList<RegionStatisticsResourcesData>();
        }
    }


    /**
     * Method called to associate a RegionStatisticsResourcesData object to this object
     * through the RegionStatisticsResourcesData foreign key attribute
     *
     * @param l RegionStatisticsResourcesData
     * @throws TorqueException
     */
    public void addRegionStatisticsResourcesData(RegionStatisticsResourcesData l) throws TorqueException
    {
        getRegionStatisticsResourcesDatas().add(l);
        l.setRegionStatistics((RegionStatistics) this);
    }

    /**
     * Method called to associate a RegionStatisticsResourcesData object to this object
     * through the RegionStatisticsResourcesData foreign key attribute using connection.
     *
     * @param l RegionStatisticsResourcesData
     * @throws TorqueException
     */
    public void addRegionStatisticsResourcesData(RegionStatisticsResourcesData l, Connection con) throws TorqueException
    {
        getRegionStatisticsResourcesDatas(con).add(l);
        l.setRegionStatistics((RegionStatistics) this);
    }

    /**
     * The criteria used to select the current contents of collRegionStatisticsResourcesDatas
     */
    private Criteria lastRegionStatisticsResourcesDatasCriteria = null;

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getRegionStatisticsResourcesDatas(new Criteria())
     *
     * @return the collection of associated objects
     * @throws TorqueException
     */
    public List<RegionStatisticsResourcesData> getRegionStatisticsResourcesDatas()
        throws TorqueException
    {
        if (collRegionStatisticsResourcesDatas == null)
        {
            collRegionStatisticsResourcesDatas = getRegionStatisticsResourcesDatas(new Criteria(10));
        }
        return collRegionStatisticsResourcesDatas;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this RegionStatistics has previously
     * been saved, it will retrieve related RegionStatisticsResourcesDatas from storage.
     * If this RegionStatistics is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     *
     * @throws TorqueException
     */
    public List<RegionStatisticsResourcesData> getRegionStatisticsResourcesDatas(Criteria criteria) throws TorqueException
    {
        if (collRegionStatisticsResourcesDatas == null)
        {
            if (isNew())
            {
               collRegionStatisticsResourcesDatas = new ArrayList<RegionStatisticsResourcesData>();
            }
            else
            {
                criteria.add(RegionStatisticsResourcesDataPeer.REGION_ID, getID() );
                collRegionStatisticsResourcesDatas = RegionStatisticsResourcesDataPeer.doSelect(criteria);
            }
        }
        else
        {
            // criteria has no effect for a new object
            if (!isNew())
            {
                // the following code is to determine if a new query is
                // called for.  If the criteria is the same as the last
                // one, just return the collection.
                criteria.add(RegionStatisticsResourcesDataPeer.REGION_ID, getID());
                if (!lastRegionStatisticsResourcesDatasCriteria.equals(criteria))
                {
                    collRegionStatisticsResourcesDatas = RegionStatisticsResourcesDataPeer.doSelect(criteria);
                }
            }
        }
        lastRegionStatisticsResourcesDatasCriteria = criteria;

        return collRegionStatisticsResourcesDatas;
    }

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getRegionStatisticsResourcesDatas(new Criteria(),Connection)
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List<RegionStatisticsResourcesData> getRegionStatisticsResourcesDatas(Connection con) throws TorqueException
    {
        if (collRegionStatisticsResourcesDatas == null)
        {
            collRegionStatisticsResourcesDatas = getRegionStatisticsResourcesDatas(new Criteria(10), con);
        }
        return collRegionStatisticsResourcesDatas;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this RegionStatistics has previously
     * been saved, it will retrieve related RegionStatisticsResourcesDatas from storage.
     * If this RegionStatistics is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List<RegionStatisticsResourcesData> getRegionStatisticsResourcesDatas(Criteria criteria, Connection con)
            throws TorqueException
    {
        if (collRegionStatisticsResourcesDatas == null)
        {
            if (isNew())
            {
               collRegionStatisticsResourcesDatas = new ArrayList<RegionStatisticsResourcesData>();
            }
            else
            {
                 criteria.add(RegionStatisticsResourcesDataPeer.REGION_ID, getID());
                 collRegionStatisticsResourcesDatas = RegionStatisticsResourcesDataPeer.doSelect(criteria, con);
             }
         }
         else
         {
             // criteria has no effect for a new object
             if (!isNew())
             {
                 // the following code is to determine if a new query is
                 // called for.  If the criteria is the same as the last
                 // one, just return the collection.
                 criteria.add(RegionStatisticsResourcesDataPeer.REGION_ID, getID());
                 if (!lastRegionStatisticsResourcesDatasCriteria.equals(criteria))
                 {
                     collRegionStatisticsResourcesDatas = RegionStatisticsResourcesDataPeer.doSelect(criteria, con);
                 }
             }
         }
         lastRegionStatisticsResourcesDatasCriteria = criteria;

         return collRegionStatisticsResourcesDatas;
     }











    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this RegionStatistics is new, it will return
     * an empty collection; or if this RegionStatistics has previously
     * been saved, it will retrieve related RegionStatisticsResourcesDatas from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in RegionStatistics.
     */
    protected List<RegionStatisticsResourcesData> getRegionStatisticsResourcesDatasJoinRegionStatisticsData(Criteria criteria)
        throws TorqueException
    {
        if (collRegionStatisticsResourcesDatas == null)
        {
            if (isNew())
            {
               collRegionStatisticsResourcesDatas = new ArrayList<RegionStatisticsResourcesData>();
            }
            else
            {
                criteria.add(RegionStatisticsResourcesDataPeer.REGION_ID, getID());
                collRegionStatisticsResourcesDatas = RegionStatisticsResourcesDataPeer.doSelectJoinRegionStatisticsData(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            criteria.add(RegionStatisticsResourcesDataPeer.REGION_ID, getID());
            if (!lastRegionStatisticsResourcesDatasCriteria.equals(criteria))
            {
                collRegionStatisticsResourcesDatas = RegionStatisticsResourcesDataPeer.doSelectJoinRegionStatisticsData(criteria);
            }
        }
        lastRegionStatisticsResourcesDatasCriteria = criteria;

        return collRegionStatisticsResourcesDatas;
    }









    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this RegionStatistics is new, it will return
     * an empty collection; or if this RegionStatistics has previously
     * been saved, it will retrieve related RegionStatisticsResourcesDatas from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in RegionStatistics.
     */
    protected List<RegionStatisticsResourcesData> getRegionStatisticsResourcesDatasJoinRegionStatistics(Criteria criteria)
        throws TorqueException
    {
        if (collRegionStatisticsResourcesDatas == null)
        {
            if (isNew())
            {
               collRegionStatisticsResourcesDatas = new ArrayList<RegionStatisticsResourcesData>();
            }
            else
            {
                criteria.add(RegionStatisticsResourcesDataPeer.REGION_ID, getID());
                collRegionStatisticsResourcesDatas = RegionStatisticsResourcesDataPeer.doSelectJoinRegionStatistics(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            criteria.add(RegionStatisticsResourcesDataPeer.REGION_ID, getID());
            if (!lastRegionStatisticsResourcesDatasCriteria.equals(criteria))
            {
                collRegionStatisticsResourcesDatas = RegionStatisticsResourcesDataPeer.doSelectJoinRegionStatistics(criteria);
            }
        }
        lastRegionStatisticsResourcesDatasCriteria = criteria;

        return collRegionStatisticsResourcesDatas;
    }



        
    private static List<String> fieldNames = null;

    /**
     * Generate a list of field names.
     *
     * @return a list of field names
     */
    public static synchronized List<String> getFieldNames()
    {
        if (fieldNames == null)
        {
            fieldNames = new ArrayList<String>();
            fieldNames.add("ID");
            fieldNames.add("ReportId");
            fieldNames.add("RegionNumber");
            fieldNames = Collections.unmodifiableList(fieldNames);
        }
        return fieldNames;
    }

    /**
     * Retrieves a field from the object by field (Java) name passed in as a String.
     *
     * @param name field name
     * @return value
     */
    public Object getByName(String name)
    {
        if (name.equals("ID"))
        {
            return new Long(getID());
        }
        if (name.equals("ReportId"))
        {
            return new Long(getReportId());
        }
        if (name.equals("RegionNumber"))
        {
            return getRegionNumber();
        }
        return null;
    }

    /**
     * Set a field in the object by field (Java) name.
     *
     * @param name field name
     * @param value field value
     * @return True if value was set, false if not (invalid name / protected field).
     * @throws IllegalArgumentException if object type of value does not match field object type.
     * @throws TorqueException If a problem occurs with the set[Field] method.
     */
    public boolean setByName(String name, Object value )
        throws TorqueException, IllegalArgumentException
    {
        if (name.equals("ID"))
        {
            if (value == null || ! (Long.class.isInstance(value)))
            {
                throw new IllegalArgumentException("setByName: value parameter was null or not a Long object.");
            }
            setID(((Long) value).longValue());
            return true;
        }
        if (name.equals("ReportId"))
        {
            if (value == null || ! (Long.class.isInstance(value)))
            {
                throw new IllegalArgumentException("setByName: value parameter was null or not a Long object.");
            }
            setReportId(((Long) value).longValue());
            return true;
        }
        if (name.equals("RegionNumber"))
        {
            // Object fields can be null
            if (value != null && ! String.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setRegionNumber((String) value);
            return true;
        }
        return false;
    }

    /**
     * Retrieves a field from the object by name passed in
     * as a String.  The String must be one of the static
     * Strings defined in this Class' Peer.
     *
     * @param name peer name
     * @return value
     */
    public Object getByPeerName(String name)
    {
        if (name.equals(RegionStatisticsPeer.ID))
        {
            return new Long(getID());
        }
        if (name.equals(RegionStatisticsPeer.REPORT_ID))
        {
            return new Long(getReportId());
        }
        if (name.equals(RegionStatisticsPeer.REGION_NUMBER))
        {
            return getRegionNumber();
        }
        return null;
    }

    /**
     * Set field values by Peer Field Name
     *
     * @param name field name
     * @param value field value
     * @return True if value was set, false if not (invalid name / protected field).
     * @throws IllegalArgumentException if object type of value does not match field object type.
     * @throws TorqueException If a problem occurs with the set[Field] method.
     */
    public boolean setByPeerName(String name, Object value)
        throws TorqueException, IllegalArgumentException
    {
      if (RegionStatisticsPeer.ID.equals(name))
        {
            return setByName("ID", value);
        }
      if (RegionStatisticsPeer.REPORT_ID.equals(name))
        {
            return setByName("ReportId", value);
        }
      if (RegionStatisticsPeer.REGION_NUMBER.equals(name))
        {
            return setByName("RegionNumber", value);
        }
        return false;
    }

    /**
     * Retrieves a field from the object by Position as specified
     * in the xml schema.  Zero-based.
     *
     * @param pos position in xml schema
     * @return value
     */
    public Object getByPosition(int pos)
    {
        if (pos == 0)
        {
            return new Long(getID());
        }
        if (pos == 1)
        {
            return new Long(getReportId());
        }
        if (pos == 2)
        {
            return getRegionNumber();
        }
        return null;
    }

    /**
     * Set field values by its position (zero based) in the XML schema.
     *
     * @param position The field position
     * @param value field value
     * @return True if value was set, false if not (invalid position / protected field).
     * @throws IllegalArgumentException if object type of value does not match field object type.
     * @throws TorqueException If a problem occurs with the set[Field] method.
     */
    public boolean setByPosition(int position, Object value)
        throws TorqueException, IllegalArgumentException
    {
    if (position == 0)
        {
            return setByName("ID", value);
        }
    if (position == 1)
        {
            return setByName("ReportId", value);
        }
    if (position == 2)
        {
            return setByName("RegionNumber", value);
        }
        return false;
    }
     
    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     *
     * @throws Exception
     */
    public void save() throws Exception
    {
        save(RegionStatisticsPeer.DATABASE_NAME);
    }

    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     * Note: this code is here because the method body is
     * auto-generated conditionally and therefore needs to be
     * in this file instead of in the super class, BaseObject.
     *
     * @param dbName
     * @throws TorqueException
     */
    public void save(String dbName) throws TorqueException
    {
        Connection con = null;
        try
        {
            con = Transaction.begin(dbName);
            save(con);
            Transaction.commit(con);
        }
        catch(TorqueException e)
        {
            Transaction.safeRollback(con);
            throw e;
        }
    }

    /** flag to prevent endless save loop, if this object is referenced
        by another object which falls in this transaction. */
    private boolean alreadyInSave = false;
    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.  This method
     * is meant to be used as part of a transaction, otherwise use
     * the save() method and the connection details will be handled
     * internally
     *
     * @param con
     * @throws TorqueException
     */
    public void save(Connection con) throws TorqueException
    {
        if (!alreadyInSave)
        {
            alreadyInSave = true;



            // If this object has been modified, then save it to the database.
            if (isModified())
            {
                if (isNew())
                {
                    RegionStatisticsPeer.doInsert((RegionStatistics) this, con);
                    setNew(false);
                }
                else
                {
                    RegionStatisticsPeer.doUpdate((RegionStatistics) this, con);
                }
            }


            if (collRegionStatisticsDatas != null)
            {
                for (int i = 0; i < collRegionStatisticsDatas.size(); i++)
                {
                    ((RegionStatisticsData) collRegionStatisticsDatas.get(i)).save(con);
                }
            }

            if (collRegionStatisticsPricesDatas != null)
            {
                for (int i = 0; i < collRegionStatisticsPricesDatas.size(); i++)
                {
                    ((RegionStatisticsPricesData) collRegionStatisticsPricesDatas.get(i)).save(con);
                }
            }

            if (collRegionStatisticsResourcesDatas != null)
            {
                for (int i = 0; i < collRegionStatisticsResourcesDatas.size(); i++)
                {
                    ((RegionStatisticsResourcesData) collRegionStatisticsResourcesDatas.get(i)).save(con);
                }
            }
            alreadyInSave = false;
        }
    }


    /**
     * Set the PrimaryKey using ObjectKey.
     *
     * @param key iD ObjectKey
     */
    public void setPrimaryKey(ObjectKey key)
        throws TorqueException
    {
        setID(((NumberKey) key).longValue());
    }

    /**
     * Set the PrimaryKey using a String.
     *
     * @param key
     */
    public void setPrimaryKey(String key) throws TorqueException
    {
        setID(Long.parseLong(key));
    }


    /**
     * returns an id that differentiates this object from others
     * of its class.
     */
    public ObjectKey getPrimaryKey()
    {
        return SimpleKey.keyFor(getID());
    }
 

    /**
     * Makes a copy of this object.
     * It creates a new object filling in the simple attributes.
     * It then fills all the association collections and sets the
     * related objects to isNew=true.
     */
    public RegionStatistics copy() throws TorqueException
    {
        return copy(true);
    }

    /**
     * Makes a copy of this object using connection.
     * It creates a new object filling in the simple attributes.
     * It then fills all the association collections and sets the
     * related objects to isNew=true.
     *
     * @param con the database connection to read associated objects.
     */
    public RegionStatistics copy(Connection con) throws TorqueException
    {
        return copy(true, con);
    }

    /**
     * Makes a copy of this object.
     * It creates a new object filling in the simple attributes.
     * If the parameter deepcopy is true, it then fills all the
     * association collections and sets the related objects to
     * isNew=true.
     *
     * @param deepcopy whether to copy the associated objects.
     */
    public RegionStatistics copy(boolean deepcopy) throws TorqueException
    {
        return copyInto(new RegionStatistics(), deepcopy);
    }

    /**
     * Makes a copy of this object using connection.
     * It creates a new object filling in the simple attributes.
     * If the parameter deepcopy is true, it then fills all the
     * association collections and sets the related objects to
     * isNew=true.
     *
     * @param deepcopy whether to copy the associated objects.
     * @param con the database connection to read associated objects.
     */
    public RegionStatistics copy(boolean deepcopy, Connection con) throws TorqueException
    {
        return copyInto(new RegionStatistics(), deepcopy, con);
    }
  
    /**
     * Fills the copyObj with the contents of this object.
     * The associated objects are also copied and treated as new objects.
     *
     * @param copyObj the object to fill.
     */
    protected RegionStatistics copyInto(RegionStatistics copyObj) throws TorqueException
    {
        return copyInto(copyObj, true);
    }

  
    /**
     * Fills the copyObj with the contents of this object using connection.
     * The associated objects are also copied and treated as new objects.
     *
     * @param copyObj the object to fill.
     * @param con the database connection to read associated objects.
     */
    protected RegionStatistics copyInto(RegionStatistics copyObj, Connection con) throws TorqueException
    {
        return copyInto(copyObj, true, con);
    }
  
    /**
     * Fills the copyObj with the contents of this object.
     * If deepcopy is true, The associated objects are also copied
     * and treated as new objects.
     *
     * @param copyObj the object to fill.
     * @param deepcopy whether the associated objects should be copied.
     */
    protected RegionStatistics copyInto(RegionStatistics copyObj, boolean deepcopy) throws TorqueException
    {
        copyObj.setID(iD);
        copyObj.setReportId(reportId);
        copyObj.setRegionNumber(regionNumber);

        copyObj.setID( 0);

        if (deepcopy)
        {


        List<RegionStatisticsData> vRegionStatisticsDatas = getRegionStatisticsDatas();
        if (vRegionStatisticsDatas != null)
        {
            for (int i = 0; i < vRegionStatisticsDatas.size(); i++)
            {
                RegionStatisticsData obj =  vRegionStatisticsDatas.get(i);
                copyObj.addRegionStatisticsData(obj.copy());
            }
        }
        else
        {
            copyObj.collRegionStatisticsDatas = null;
        }


        List<RegionStatisticsPricesData> vRegionStatisticsPricesDatas = getRegionStatisticsPricesDatas();
        if (vRegionStatisticsPricesDatas != null)
        {
            for (int i = 0; i < vRegionStatisticsPricesDatas.size(); i++)
            {
                RegionStatisticsPricesData obj =  vRegionStatisticsPricesDatas.get(i);
                copyObj.addRegionStatisticsPricesData(obj.copy());
            }
        }
        else
        {
            copyObj.collRegionStatisticsPricesDatas = null;
        }


        List<RegionStatisticsResourcesData> vRegionStatisticsResourcesDatas = getRegionStatisticsResourcesDatas();
        if (vRegionStatisticsResourcesDatas != null)
        {
            for (int i = 0; i < vRegionStatisticsResourcesDatas.size(); i++)
            {
                RegionStatisticsResourcesData obj =  vRegionStatisticsResourcesDatas.get(i);
                copyObj.addRegionStatisticsResourcesData(obj.copy());
            }
        }
        else
        {
            copyObj.collRegionStatisticsResourcesDatas = null;
        }
        }
        return copyObj;
    }
        
    
    /**
     * Fills the copyObj with the contents of this object using connection.
     * If deepcopy is true, The associated objects are also copied
     * and treated as new objects.
     *
     * @param copyObj the object to fill.
     * @param deepcopy whether the associated objects should be copied.
     * @param con the database connection to read associated objects.
     */
    protected RegionStatistics copyInto(RegionStatistics copyObj, boolean deepcopy, Connection con) throws TorqueException
    {
        copyObj.setID(iD);
        copyObj.setReportId(reportId);
        copyObj.setRegionNumber(regionNumber);

        copyObj.setID( 0);

        if (deepcopy)
        {


        List<RegionStatisticsData> vRegionStatisticsDatas = getRegionStatisticsDatas(con);
        if (vRegionStatisticsDatas != null)
        {
            for (int i = 0; i < vRegionStatisticsDatas.size(); i++)
            {
                RegionStatisticsData obj =  vRegionStatisticsDatas.get(i);
                copyObj.addRegionStatisticsData(obj.copy(con), con);
            }
        }
        else
        {
            copyObj.collRegionStatisticsDatas = null;
        }


        List<RegionStatisticsPricesData> vRegionStatisticsPricesDatas = getRegionStatisticsPricesDatas(con);
        if (vRegionStatisticsPricesDatas != null)
        {
            for (int i = 0; i < vRegionStatisticsPricesDatas.size(); i++)
            {
                RegionStatisticsPricesData obj =  vRegionStatisticsPricesDatas.get(i);
                copyObj.addRegionStatisticsPricesData(obj.copy(con), con);
            }
        }
        else
        {
            copyObj.collRegionStatisticsPricesDatas = null;
        }


        List<RegionStatisticsResourcesData> vRegionStatisticsResourcesDatas = getRegionStatisticsResourcesDatas(con);
        if (vRegionStatisticsResourcesDatas != null)
        {
            for (int i = 0; i < vRegionStatisticsResourcesDatas.size(); i++)
            {
                RegionStatisticsResourcesData obj =  vRegionStatisticsResourcesDatas.get(i);
                copyObj.addRegionStatisticsResourcesData(obj.copy(con), con);
            }
        }
        else
        {
            copyObj.collRegionStatisticsResourcesDatas = null;
        }
        }
        return copyObj;
    }
    
    

    /**
     * returns a peer instance associated with this om.  Since Peer classes
     * are not to have any instance attributes, this method returns the
     * same instance for all member of this class. The method could therefore
     * be static, but this would prevent one from overriding the behavior.
     */
    public RegionStatisticsPeer getPeer()
    {
        return peer;
    }

    /**
     * Retrieves the TableMap object related to this Table data without
     * compiler warnings of using getPeer().getTableMap().
     *
     * @return The associated TableMap object.
     */
    public TableMap getTableMap() throws TorqueException
    {
        return RegionStatisticsPeer.getTableMap();
    }


    public String toString()
    {
        StringBuffer str = new StringBuffer();
        str.append("RegionStatistics:\n");
        str.append("ID = ")
           .append(getID())
           .append("\n");
        str.append("ReportId = ")
           .append(getReportId())
           .append("\n");
        str.append("RegionNumber = ")
           .append(getRegionNumber())
           .append("\n");
        return(str.toString());
    }
}
