package magellan.plugin.statistics.torque;


import org.apache.torque.om.Persistent;

/**
 * Contains informations about turn specific region resources
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Wed May 21 18:19:59 CEST 2008]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public  class RegionStatisticsResourcesData
    extends magellan.plugin.statistics.torque.BaseRegionStatisticsResourcesData
    implements Persistent
{
    /** Serial version */
    private static final long serialVersionUID = 1211386799035L;

}
