package magellan.plugin.statistics.torque;


import java.math.BigDecimal;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;

import org.apache.commons.lang.ObjectUtils;
import org.apache.torque.TorqueException;
import org.apache.torque.map.TableMap;
import org.apache.torque.om.BaseObject;
import org.apache.torque.om.ComboKey;
import org.apache.torque.om.DateKey;
import org.apache.torque.om.NumberKey;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.om.StringKey;
import org.apache.torque.om.Persistent;
import org.apache.torque.util.Criteria;
import org.apache.torque.util.Transaction;





/**
 * Contains informations about units
 *
 * This class was autogenerated by Torque on:
 *
 * [Fri May 23 08:09:17 CEST 2008]
 *
 * You should not use this class directly.  It should not even be
 * extended all references should be to UnitStatistics
 */
public abstract class BaseUnitStatistics extends BaseObject
{
    /** Serial version */
    private static final long serialVersionUID = 1211522957714L;

    /** The Peer class */
    private static final UnitStatisticsPeer peer =
        new UnitStatisticsPeer();


    /** The value for the iD field */
    private long iD;

    /** The value for the reportId field */
    private long reportId;

    /** The value for the unitNumber field */
    private String unitNumber;


    /**
     * Get the ID
     *
     * @return long
     */
    public long getID()
    {
        return iD;
    }


    /**
     * Set the value of ID
     *
     * @param v new value
     */
    public void setID(long v) throws TorqueException
    {

        if (this.iD != v)
        {
            this.iD = v;
            setModified(true);
        }



        // update associated UnitStatisticsData
        if (collUnitStatisticsDatas != null)
        {
            for (int i = 0; i < collUnitStatisticsDatas.size(); i++)
            {
                ((UnitStatisticsData) collUnitStatisticsDatas.get(i))
                        .setUnitId(v);
            }
        }

        // update associated UnitStatisticsSkillData
        if (collUnitStatisticsSkillDatas != null)
        {
            for (int i = 0; i < collUnitStatisticsSkillDatas.size(); i++)
            {
                ((UnitStatisticsSkillData) collUnitStatisticsSkillDatas.get(i))
                        .setUnitId(v);
            }
        }

        // update associated UnitStatisticsItemData
        if (collUnitStatisticsItemDatas != null)
        {
            for (int i = 0; i < collUnitStatisticsItemDatas.size(); i++)
            {
                ((UnitStatisticsItemData) collUnitStatisticsItemDatas.get(i))
                        .setUnitId(v);
            }
        }
    }

    /**
     * Get the ReportId
     *
     * @return long
     */
    public long getReportId()
    {
        return reportId;
    }


    /**
     * Set the value of ReportId
     *
     * @param v new value
     */
    public void setReportId(long v) throws TorqueException
    {

        if (this.reportId != v)
        {
            this.reportId = v;
            setModified(true);
        }


        if (aReport != null && !(aReport.getID() == v))
        {
            aReport = null;
        }

    }

    /**
     * Get the UnitNumber
     *
     * @return String
     */
    public String getUnitNumber()
    {
        return unitNumber;
    }


    /**
     * Set the value of UnitNumber
     *
     * @param v new value
     */
    public void setUnitNumber(String v) 
    {

        if (!ObjectUtils.equals(this.unitNumber, v))
        {
            this.unitNumber = v;
            setModified(true);
        }


    }

    



    private Report aReport;

    /**
     * Declares an association between this object and a Report object
     *
     * @param v Report
     * @throws TorqueException
     */
    public void setReport(Report v) throws TorqueException
    {
        if (v == null)
        {
            setReportId( 0);
        }
        else
        {
            setReportId(v.getID());
        }
        aReport = v;
    }


    /**
     * Returns the associated Report object.
     * If it was not retrieved before, the object is retrieved from
     * the database
     *
     * @return the associated Report object
     * @throws TorqueException
     */
    public Report getReport()
        throws TorqueException
    {
        if (aReport == null && (this.reportId != 0))
        {
            aReport = ReportPeer.retrieveByPK(SimpleKey.keyFor(this.reportId));
        }
        return aReport;
    }

    /**
     * Return the associated Report object
     * If it was not retrieved before, the object is retrieved from
     * the database using the passed connection
     *
     * @param connection the connection used to retrieve the associated object
     *        from the database, if it was not retrieved before
     * @return the associated Report object
     * @throws TorqueException
     */
    public Report getReport(Connection connection)
        throws TorqueException
    {
        if (aReport == null && (this.reportId != 0))
        {
            aReport = ReportPeer.retrieveByPK(SimpleKey.keyFor(this.reportId), connection);
        }
        return aReport;
    }

    /**
     * Provides convenient way to set a relationship based on a
     * ObjectKey, for example
     * <code>bar.setFooKey(foo.getPrimaryKey())</code>
     *
     */
    public void setReportKey(ObjectKey key) throws TorqueException
    {

        setReportId(((NumberKey) key).longValue());
    }
   


    /**
     * Collection to store aggregation of collUnitStatisticsDatas
     */
    protected List<UnitStatisticsData> collUnitStatisticsDatas;

    /**
     * Temporary storage of collUnitStatisticsDatas to save a possible db hit in
     * the event objects are add to the collection, but the
     * complete collection is never requested.
     */
    protected void initUnitStatisticsDatas()
    {
        if (collUnitStatisticsDatas == null)
        {
            collUnitStatisticsDatas = new ArrayList<UnitStatisticsData>();
        }
    }


    /**
     * Method called to associate a UnitStatisticsData object to this object
     * through the UnitStatisticsData foreign key attribute
     *
     * @param l UnitStatisticsData
     * @throws TorqueException
     */
    public void addUnitStatisticsData(UnitStatisticsData l) throws TorqueException
    {
        getUnitStatisticsDatas().add(l);
        l.setUnitStatistics((UnitStatistics) this);
    }

    /**
     * Method called to associate a UnitStatisticsData object to this object
     * through the UnitStatisticsData foreign key attribute using connection.
     *
     * @param l UnitStatisticsData
     * @throws TorqueException
     */
    public void addUnitStatisticsData(UnitStatisticsData l, Connection con) throws TorqueException
    {
        getUnitStatisticsDatas(con).add(l);
        l.setUnitStatistics((UnitStatistics) this);
    }

    /**
     * The criteria used to select the current contents of collUnitStatisticsDatas
     */
    private Criteria lastUnitStatisticsDatasCriteria = null;

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getUnitStatisticsDatas(new Criteria())
     *
     * @return the collection of associated objects
     * @throws TorqueException
     */
    public List<UnitStatisticsData> getUnitStatisticsDatas()
        throws TorqueException
    {
        if (collUnitStatisticsDatas == null)
        {
            collUnitStatisticsDatas = getUnitStatisticsDatas(new Criteria(10));
        }
        return collUnitStatisticsDatas;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this UnitStatistics has previously
     * been saved, it will retrieve related UnitStatisticsDatas from storage.
     * If this UnitStatistics is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     *
     * @throws TorqueException
     */
    public List<UnitStatisticsData> getUnitStatisticsDatas(Criteria criteria) throws TorqueException
    {
        if (collUnitStatisticsDatas == null)
        {
            if (isNew())
            {
               collUnitStatisticsDatas = new ArrayList<UnitStatisticsData>();
            }
            else
            {
                criteria.add(UnitStatisticsDataPeer.UNIT_ID, getID() );
                collUnitStatisticsDatas = UnitStatisticsDataPeer.doSelect(criteria);
            }
        }
        else
        {
            // criteria has no effect for a new object
            if (!isNew())
            {
                // the following code is to determine if a new query is
                // called for.  If the criteria is the same as the last
                // one, just return the collection.
                criteria.add(UnitStatisticsDataPeer.UNIT_ID, getID());
                if (!lastUnitStatisticsDatasCriteria.equals(criteria))
                {
                    collUnitStatisticsDatas = UnitStatisticsDataPeer.doSelect(criteria);
                }
            }
        }
        lastUnitStatisticsDatasCriteria = criteria;

        return collUnitStatisticsDatas;
    }

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getUnitStatisticsDatas(new Criteria(),Connection)
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List<UnitStatisticsData> getUnitStatisticsDatas(Connection con) throws TorqueException
    {
        if (collUnitStatisticsDatas == null)
        {
            collUnitStatisticsDatas = getUnitStatisticsDatas(new Criteria(10), con);
        }
        return collUnitStatisticsDatas;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this UnitStatistics has previously
     * been saved, it will retrieve related UnitStatisticsDatas from storage.
     * If this UnitStatistics is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List<UnitStatisticsData> getUnitStatisticsDatas(Criteria criteria, Connection con)
            throws TorqueException
    {
        if (collUnitStatisticsDatas == null)
        {
            if (isNew())
            {
               collUnitStatisticsDatas = new ArrayList<UnitStatisticsData>();
            }
            else
            {
                 criteria.add(UnitStatisticsDataPeer.UNIT_ID, getID());
                 collUnitStatisticsDatas = UnitStatisticsDataPeer.doSelect(criteria, con);
             }
         }
         else
         {
             // criteria has no effect for a new object
             if (!isNew())
             {
                 // the following code is to determine if a new query is
                 // called for.  If the criteria is the same as the last
                 // one, just return the collection.
                 criteria.add(UnitStatisticsDataPeer.UNIT_ID, getID());
                 if (!lastUnitStatisticsDatasCriteria.equals(criteria))
                 {
                     collUnitStatisticsDatas = UnitStatisticsDataPeer.doSelect(criteria, con);
                 }
             }
         }
         lastUnitStatisticsDatasCriteria = criteria;

         return collUnitStatisticsDatas;
     }











    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this UnitStatistics is new, it will return
     * an empty collection; or if this UnitStatistics has previously
     * been saved, it will retrieve related UnitStatisticsDatas from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in UnitStatistics.
     */
    protected List<UnitStatisticsData> getUnitStatisticsDatasJoinUnitStatistics(Criteria criteria)
        throws TorqueException
    {
        if (collUnitStatisticsDatas == null)
        {
            if (isNew())
            {
               collUnitStatisticsDatas = new ArrayList<UnitStatisticsData>();
            }
            else
            {
                criteria.add(UnitStatisticsDataPeer.UNIT_ID, getID());
                collUnitStatisticsDatas = UnitStatisticsDataPeer.doSelectJoinUnitStatistics(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            criteria.add(UnitStatisticsDataPeer.UNIT_ID, getID());
            if (!lastUnitStatisticsDatasCriteria.equals(criteria))
            {
                collUnitStatisticsDatas = UnitStatisticsDataPeer.doSelectJoinUnitStatistics(criteria);
            }
        }
        lastUnitStatisticsDatasCriteria = criteria;

        return collUnitStatisticsDatas;
    }





    /**
     * Collection to store aggregation of collUnitStatisticsSkillDatas
     */
    protected List<UnitStatisticsSkillData> collUnitStatisticsSkillDatas;

    /**
     * Temporary storage of collUnitStatisticsSkillDatas to save a possible db hit in
     * the event objects are add to the collection, but the
     * complete collection is never requested.
     */
    protected void initUnitStatisticsSkillDatas()
    {
        if (collUnitStatisticsSkillDatas == null)
        {
            collUnitStatisticsSkillDatas = new ArrayList<UnitStatisticsSkillData>();
        }
    }


    /**
     * Method called to associate a UnitStatisticsSkillData object to this object
     * through the UnitStatisticsSkillData foreign key attribute
     *
     * @param l UnitStatisticsSkillData
     * @throws TorqueException
     */
    public void addUnitStatisticsSkillData(UnitStatisticsSkillData l) throws TorqueException
    {
        getUnitStatisticsSkillDatas().add(l);
        l.setUnitStatistics((UnitStatistics) this);
    }

    /**
     * Method called to associate a UnitStatisticsSkillData object to this object
     * through the UnitStatisticsSkillData foreign key attribute using connection.
     *
     * @param l UnitStatisticsSkillData
     * @throws TorqueException
     */
    public void addUnitStatisticsSkillData(UnitStatisticsSkillData l, Connection con) throws TorqueException
    {
        getUnitStatisticsSkillDatas(con).add(l);
        l.setUnitStatistics((UnitStatistics) this);
    }

    /**
     * The criteria used to select the current contents of collUnitStatisticsSkillDatas
     */
    private Criteria lastUnitStatisticsSkillDatasCriteria = null;

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getUnitStatisticsSkillDatas(new Criteria())
     *
     * @return the collection of associated objects
     * @throws TorqueException
     */
    public List<UnitStatisticsSkillData> getUnitStatisticsSkillDatas()
        throws TorqueException
    {
        if (collUnitStatisticsSkillDatas == null)
        {
            collUnitStatisticsSkillDatas = getUnitStatisticsSkillDatas(new Criteria(10));
        }
        return collUnitStatisticsSkillDatas;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this UnitStatistics has previously
     * been saved, it will retrieve related UnitStatisticsSkillDatas from storage.
     * If this UnitStatistics is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     *
     * @throws TorqueException
     */
    public List<UnitStatisticsSkillData> getUnitStatisticsSkillDatas(Criteria criteria) throws TorqueException
    {
        if (collUnitStatisticsSkillDatas == null)
        {
            if (isNew())
            {
               collUnitStatisticsSkillDatas = new ArrayList<UnitStatisticsSkillData>();
            }
            else
            {
                criteria.add(UnitStatisticsSkillDataPeer.UNIT_ID, getID() );
                collUnitStatisticsSkillDatas = UnitStatisticsSkillDataPeer.doSelect(criteria);
            }
        }
        else
        {
            // criteria has no effect for a new object
            if (!isNew())
            {
                // the following code is to determine if a new query is
                // called for.  If the criteria is the same as the last
                // one, just return the collection.
                criteria.add(UnitStatisticsSkillDataPeer.UNIT_ID, getID());
                if (!lastUnitStatisticsSkillDatasCriteria.equals(criteria))
                {
                    collUnitStatisticsSkillDatas = UnitStatisticsSkillDataPeer.doSelect(criteria);
                }
            }
        }
        lastUnitStatisticsSkillDatasCriteria = criteria;

        return collUnitStatisticsSkillDatas;
    }

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getUnitStatisticsSkillDatas(new Criteria(),Connection)
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List<UnitStatisticsSkillData> getUnitStatisticsSkillDatas(Connection con) throws TorqueException
    {
        if (collUnitStatisticsSkillDatas == null)
        {
            collUnitStatisticsSkillDatas = getUnitStatisticsSkillDatas(new Criteria(10), con);
        }
        return collUnitStatisticsSkillDatas;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this UnitStatistics has previously
     * been saved, it will retrieve related UnitStatisticsSkillDatas from storage.
     * If this UnitStatistics is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List<UnitStatisticsSkillData> getUnitStatisticsSkillDatas(Criteria criteria, Connection con)
            throws TorqueException
    {
        if (collUnitStatisticsSkillDatas == null)
        {
            if (isNew())
            {
               collUnitStatisticsSkillDatas = new ArrayList<UnitStatisticsSkillData>();
            }
            else
            {
                 criteria.add(UnitStatisticsSkillDataPeer.UNIT_ID, getID());
                 collUnitStatisticsSkillDatas = UnitStatisticsSkillDataPeer.doSelect(criteria, con);
             }
         }
         else
         {
             // criteria has no effect for a new object
             if (!isNew())
             {
                 // the following code is to determine if a new query is
                 // called for.  If the criteria is the same as the last
                 // one, just return the collection.
                 criteria.add(UnitStatisticsSkillDataPeer.UNIT_ID, getID());
                 if (!lastUnitStatisticsSkillDatasCriteria.equals(criteria))
                 {
                     collUnitStatisticsSkillDatas = UnitStatisticsSkillDataPeer.doSelect(criteria, con);
                 }
             }
         }
         lastUnitStatisticsSkillDatasCriteria = criteria;

         return collUnitStatisticsSkillDatas;
     }











    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this UnitStatistics is new, it will return
     * an empty collection; or if this UnitStatistics has previously
     * been saved, it will retrieve related UnitStatisticsSkillDatas from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in UnitStatistics.
     */
    protected List<UnitStatisticsSkillData> getUnitStatisticsSkillDatasJoinUnitStatisticsData(Criteria criteria)
        throws TorqueException
    {
        if (collUnitStatisticsSkillDatas == null)
        {
            if (isNew())
            {
               collUnitStatisticsSkillDatas = new ArrayList<UnitStatisticsSkillData>();
            }
            else
            {
                criteria.add(UnitStatisticsSkillDataPeer.UNIT_ID, getID());
                collUnitStatisticsSkillDatas = UnitStatisticsSkillDataPeer.doSelectJoinUnitStatisticsData(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            criteria.add(UnitStatisticsSkillDataPeer.UNIT_ID, getID());
            if (!lastUnitStatisticsSkillDatasCriteria.equals(criteria))
            {
                collUnitStatisticsSkillDatas = UnitStatisticsSkillDataPeer.doSelectJoinUnitStatisticsData(criteria);
            }
        }
        lastUnitStatisticsSkillDatasCriteria = criteria;

        return collUnitStatisticsSkillDatas;
    }









    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this UnitStatistics is new, it will return
     * an empty collection; or if this UnitStatistics has previously
     * been saved, it will retrieve related UnitStatisticsSkillDatas from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in UnitStatistics.
     */
    protected List<UnitStatisticsSkillData> getUnitStatisticsSkillDatasJoinUnitStatistics(Criteria criteria)
        throws TorqueException
    {
        if (collUnitStatisticsSkillDatas == null)
        {
            if (isNew())
            {
               collUnitStatisticsSkillDatas = new ArrayList<UnitStatisticsSkillData>();
            }
            else
            {
                criteria.add(UnitStatisticsSkillDataPeer.UNIT_ID, getID());
                collUnitStatisticsSkillDatas = UnitStatisticsSkillDataPeer.doSelectJoinUnitStatistics(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            criteria.add(UnitStatisticsSkillDataPeer.UNIT_ID, getID());
            if (!lastUnitStatisticsSkillDatasCriteria.equals(criteria))
            {
                collUnitStatisticsSkillDatas = UnitStatisticsSkillDataPeer.doSelectJoinUnitStatistics(criteria);
            }
        }
        lastUnitStatisticsSkillDatasCriteria = criteria;

        return collUnitStatisticsSkillDatas;
    }





    /**
     * Collection to store aggregation of collUnitStatisticsItemDatas
     */
    protected List<UnitStatisticsItemData> collUnitStatisticsItemDatas;

    /**
     * Temporary storage of collUnitStatisticsItemDatas to save a possible db hit in
     * the event objects are add to the collection, but the
     * complete collection is never requested.
     */
    protected void initUnitStatisticsItemDatas()
    {
        if (collUnitStatisticsItemDatas == null)
        {
            collUnitStatisticsItemDatas = new ArrayList<UnitStatisticsItemData>();
        }
    }


    /**
     * Method called to associate a UnitStatisticsItemData object to this object
     * through the UnitStatisticsItemData foreign key attribute
     *
     * @param l UnitStatisticsItemData
     * @throws TorqueException
     */
    public void addUnitStatisticsItemData(UnitStatisticsItemData l) throws TorqueException
    {
        getUnitStatisticsItemDatas().add(l);
        l.setUnitStatistics((UnitStatistics) this);
    }

    /**
     * Method called to associate a UnitStatisticsItemData object to this object
     * through the UnitStatisticsItemData foreign key attribute using connection.
     *
     * @param l UnitStatisticsItemData
     * @throws TorqueException
     */
    public void addUnitStatisticsItemData(UnitStatisticsItemData l, Connection con) throws TorqueException
    {
        getUnitStatisticsItemDatas(con).add(l);
        l.setUnitStatistics((UnitStatistics) this);
    }

    /**
     * The criteria used to select the current contents of collUnitStatisticsItemDatas
     */
    private Criteria lastUnitStatisticsItemDatasCriteria = null;

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getUnitStatisticsItemDatas(new Criteria())
     *
     * @return the collection of associated objects
     * @throws TorqueException
     */
    public List<UnitStatisticsItemData> getUnitStatisticsItemDatas()
        throws TorqueException
    {
        if (collUnitStatisticsItemDatas == null)
        {
            collUnitStatisticsItemDatas = getUnitStatisticsItemDatas(new Criteria(10));
        }
        return collUnitStatisticsItemDatas;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this UnitStatistics has previously
     * been saved, it will retrieve related UnitStatisticsItemDatas from storage.
     * If this UnitStatistics is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     *
     * @throws TorqueException
     */
    public List<UnitStatisticsItemData> getUnitStatisticsItemDatas(Criteria criteria) throws TorqueException
    {
        if (collUnitStatisticsItemDatas == null)
        {
            if (isNew())
            {
               collUnitStatisticsItemDatas = new ArrayList<UnitStatisticsItemData>();
            }
            else
            {
                criteria.add(UnitStatisticsItemDataPeer.UNIT_ID, getID() );
                collUnitStatisticsItemDatas = UnitStatisticsItemDataPeer.doSelect(criteria);
            }
        }
        else
        {
            // criteria has no effect for a new object
            if (!isNew())
            {
                // the following code is to determine if a new query is
                // called for.  If the criteria is the same as the last
                // one, just return the collection.
                criteria.add(UnitStatisticsItemDataPeer.UNIT_ID, getID());
                if (!lastUnitStatisticsItemDatasCriteria.equals(criteria))
                {
                    collUnitStatisticsItemDatas = UnitStatisticsItemDataPeer.doSelect(criteria);
                }
            }
        }
        lastUnitStatisticsItemDatasCriteria = criteria;

        return collUnitStatisticsItemDatas;
    }

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getUnitStatisticsItemDatas(new Criteria(),Connection)
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List<UnitStatisticsItemData> getUnitStatisticsItemDatas(Connection con) throws TorqueException
    {
        if (collUnitStatisticsItemDatas == null)
        {
            collUnitStatisticsItemDatas = getUnitStatisticsItemDatas(new Criteria(10), con);
        }
        return collUnitStatisticsItemDatas;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this UnitStatistics has previously
     * been saved, it will retrieve related UnitStatisticsItemDatas from storage.
     * If this UnitStatistics is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List<UnitStatisticsItemData> getUnitStatisticsItemDatas(Criteria criteria, Connection con)
            throws TorqueException
    {
        if (collUnitStatisticsItemDatas == null)
        {
            if (isNew())
            {
               collUnitStatisticsItemDatas = new ArrayList<UnitStatisticsItemData>();
            }
            else
            {
                 criteria.add(UnitStatisticsItemDataPeer.UNIT_ID, getID());
                 collUnitStatisticsItemDatas = UnitStatisticsItemDataPeer.doSelect(criteria, con);
             }
         }
         else
         {
             // criteria has no effect for a new object
             if (!isNew())
             {
                 // the following code is to determine if a new query is
                 // called for.  If the criteria is the same as the last
                 // one, just return the collection.
                 criteria.add(UnitStatisticsItemDataPeer.UNIT_ID, getID());
                 if (!lastUnitStatisticsItemDatasCriteria.equals(criteria))
                 {
                     collUnitStatisticsItemDatas = UnitStatisticsItemDataPeer.doSelect(criteria, con);
                 }
             }
         }
         lastUnitStatisticsItemDatasCriteria = criteria;

         return collUnitStatisticsItemDatas;
     }











    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this UnitStatistics is new, it will return
     * an empty collection; or if this UnitStatistics has previously
     * been saved, it will retrieve related UnitStatisticsItemDatas from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in UnitStatistics.
     */
    protected List<UnitStatisticsItemData> getUnitStatisticsItemDatasJoinUnitStatisticsData(Criteria criteria)
        throws TorqueException
    {
        if (collUnitStatisticsItemDatas == null)
        {
            if (isNew())
            {
               collUnitStatisticsItemDatas = new ArrayList<UnitStatisticsItemData>();
            }
            else
            {
                criteria.add(UnitStatisticsItemDataPeer.UNIT_ID, getID());
                collUnitStatisticsItemDatas = UnitStatisticsItemDataPeer.doSelectJoinUnitStatisticsData(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            criteria.add(UnitStatisticsItemDataPeer.UNIT_ID, getID());
            if (!lastUnitStatisticsItemDatasCriteria.equals(criteria))
            {
                collUnitStatisticsItemDatas = UnitStatisticsItemDataPeer.doSelectJoinUnitStatisticsData(criteria);
            }
        }
        lastUnitStatisticsItemDatasCriteria = criteria;

        return collUnitStatisticsItemDatas;
    }









    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this UnitStatistics is new, it will return
     * an empty collection; or if this UnitStatistics has previously
     * been saved, it will retrieve related UnitStatisticsItemDatas from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in UnitStatistics.
     */
    protected List<UnitStatisticsItemData> getUnitStatisticsItemDatasJoinUnitStatistics(Criteria criteria)
        throws TorqueException
    {
        if (collUnitStatisticsItemDatas == null)
        {
            if (isNew())
            {
               collUnitStatisticsItemDatas = new ArrayList<UnitStatisticsItemData>();
            }
            else
            {
                criteria.add(UnitStatisticsItemDataPeer.UNIT_ID, getID());
                collUnitStatisticsItemDatas = UnitStatisticsItemDataPeer.doSelectJoinUnitStatistics(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            criteria.add(UnitStatisticsItemDataPeer.UNIT_ID, getID());
            if (!lastUnitStatisticsItemDatasCriteria.equals(criteria))
            {
                collUnitStatisticsItemDatas = UnitStatisticsItemDataPeer.doSelectJoinUnitStatistics(criteria);
            }
        }
        lastUnitStatisticsItemDatasCriteria = criteria;

        return collUnitStatisticsItemDatas;
    }



        
    private static List<String> fieldNames = null;

    /**
     * Generate a list of field names.
     *
     * @return a list of field names
     */
    public static synchronized List<String> getFieldNames()
    {
        if (fieldNames == null)
        {
            fieldNames = new ArrayList<String>();
            fieldNames.add("ID");
            fieldNames.add("ReportId");
            fieldNames.add("UnitNumber");
            fieldNames = Collections.unmodifiableList(fieldNames);
        }
        return fieldNames;
    }

    /**
     * Retrieves a field from the object by field (Java) name passed in as a String.
     *
     * @param name field name
     * @return value
     */
    public Object getByName(String name)
    {
        if (name.equals("ID"))
        {
            return new Long(getID());
        }
        if (name.equals("ReportId"))
        {
            return new Long(getReportId());
        }
        if (name.equals("UnitNumber"))
        {
            return getUnitNumber();
        }
        return null;
    }

    /**
     * Set a field in the object by field (Java) name.
     *
     * @param name field name
     * @param value field value
     * @return True if value was set, false if not (invalid name / protected field).
     * @throws IllegalArgumentException if object type of value does not match field object type.
     * @throws TorqueException If a problem occurs with the set[Field] method.
     */
    public boolean setByName(String name, Object value )
        throws TorqueException, IllegalArgumentException
    {
        if (name.equals("ID"))
        {
            if (value == null || ! (Long.class.isInstance(value)))
            {
                throw new IllegalArgumentException("setByName: value parameter was null or not a Long object.");
            }
            setID(((Long) value).longValue());
            return true;
        }
        if (name.equals("ReportId"))
        {
            if (value == null || ! (Long.class.isInstance(value)))
            {
                throw new IllegalArgumentException("setByName: value parameter was null or not a Long object.");
            }
            setReportId(((Long) value).longValue());
            return true;
        }
        if (name.equals("UnitNumber"))
        {
            // Object fields can be null
            if (value != null && ! String.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setUnitNumber((String) value);
            return true;
        }
        return false;
    }

    /**
     * Retrieves a field from the object by name passed in
     * as a String.  The String must be one of the static
     * Strings defined in this Class' Peer.
     *
     * @param name peer name
     * @return value
     */
    public Object getByPeerName(String name)
    {
        if (name.equals(UnitStatisticsPeer.ID))
        {
            return new Long(getID());
        }
        if (name.equals(UnitStatisticsPeer.REPORT_ID))
        {
            return new Long(getReportId());
        }
        if (name.equals(UnitStatisticsPeer.UNIT_NUMBER))
        {
            return getUnitNumber();
        }
        return null;
    }

    /**
     * Set field values by Peer Field Name
     *
     * @param name field name
     * @param value field value
     * @return True if value was set, false if not (invalid name / protected field).
     * @throws IllegalArgumentException if object type of value does not match field object type.
     * @throws TorqueException If a problem occurs with the set[Field] method.
     */
    public boolean setByPeerName(String name, Object value)
        throws TorqueException, IllegalArgumentException
    {
      if (UnitStatisticsPeer.ID.equals(name))
        {
            return setByName("ID", value);
        }
      if (UnitStatisticsPeer.REPORT_ID.equals(name))
        {
            return setByName("ReportId", value);
        }
      if (UnitStatisticsPeer.UNIT_NUMBER.equals(name))
        {
            return setByName("UnitNumber", value);
        }
        return false;
    }

    /**
     * Retrieves a field from the object by Position as specified
     * in the xml schema.  Zero-based.
     *
     * @param pos position in xml schema
     * @return value
     */
    public Object getByPosition(int pos)
    {
        if (pos == 0)
        {
            return new Long(getID());
        }
        if (pos == 1)
        {
            return new Long(getReportId());
        }
        if (pos == 2)
        {
            return getUnitNumber();
        }
        return null;
    }

    /**
     * Set field values by its position (zero based) in the XML schema.
     *
     * @param position The field position
     * @param value field value
     * @return True if value was set, false if not (invalid position / protected field).
     * @throws IllegalArgumentException if object type of value does not match field object type.
     * @throws TorqueException If a problem occurs with the set[Field] method.
     */
    public boolean setByPosition(int position, Object value)
        throws TorqueException, IllegalArgumentException
    {
    if (position == 0)
        {
            return setByName("ID", value);
        }
    if (position == 1)
        {
            return setByName("ReportId", value);
        }
    if (position == 2)
        {
            return setByName("UnitNumber", value);
        }
        return false;
    }
     
    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     *
     * @throws Exception
     */
    public void save() throws Exception
    {
        save(UnitStatisticsPeer.DATABASE_NAME);
    }

    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     * Note: this code is here because the method body is
     * auto-generated conditionally and therefore needs to be
     * in this file instead of in the super class, BaseObject.
     *
     * @param dbName
     * @throws TorqueException
     */
    public void save(String dbName) throws TorqueException
    {
        Connection con = null;
        try
        {
            con = Transaction.begin(dbName);
            save(con);
            Transaction.commit(con);
        }
        catch(TorqueException e)
        {
            Transaction.safeRollback(con);
            throw e;
        }
    }

    /** flag to prevent endless save loop, if this object is referenced
        by another object which falls in this transaction. */
    private boolean alreadyInSave = false;
    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.  This method
     * is meant to be used as part of a transaction, otherwise use
     * the save() method and the connection details will be handled
     * internally
     *
     * @param con
     * @throws TorqueException
     */
    public void save(Connection con) throws TorqueException
    {
        if (!alreadyInSave)
        {
            alreadyInSave = true;



            // If this object has been modified, then save it to the database.
            if (isModified())
            {
                if (isNew())
                {
                    UnitStatisticsPeer.doInsert((UnitStatistics) this, con);
                    setNew(false);
                }
                else
                {
                    UnitStatisticsPeer.doUpdate((UnitStatistics) this, con);
                }
            }


            if (collUnitStatisticsDatas != null)
            {
                for (int i = 0; i < collUnitStatisticsDatas.size(); i++)
                {
                    ((UnitStatisticsData) collUnitStatisticsDatas.get(i)).save(con);
                }
            }

            if (collUnitStatisticsSkillDatas != null)
            {
                for (int i = 0; i < collUnitStatisticsSkillDatas.size(); i++)
                {
                    ((UnitStatisticsSkillData) collUnitStatisticsSkillDatas.get(i)).save(con);
                }
            }

            if (collUnitStatisticsItemDatas != null)
            {
                for (int i = 0; i < collUnitStatisticsItemDatas.size(); i++)
                {
                    ((UnitStatisticsItemData) collUnitStatisticsItemDatas.get(i)).save(con);
                }
            }
            alreadyInSave = false;
        }
    }


    /**
     * Set the PrimaryKey using ObjectKey.
     *
     * @param key iD ObjectKey
     */
    public void setPrimaryKey(ObjectKey key)
        throws TorqueException
    {
        setID(((NumberKey) key).longValue());
    }

    /**
     * Set the PrimaryKey using a String.
     *
     * @param key
     */
    public void setPrimaryKey(String key) throws TorqueException
    {
        setID(Long.parseLong(key));
    }


    /**
     * returns an id that differentiates this object from others
     * of its class.
     */
    public ObjectKey getPrimaryKey()
    {
        return SimpleKey.keyFor(getID());
    }
 

    /**
     * Makes a copy of this object.
     * It creates a new object filling in the simple attributes.
     * It then fills all the association collections and sets the
     * related objects to isNew=true.
     */
    public UnitStatistics copy() throws TorqueException
    {
        return copy(true);
    }

    /**
     * Makes a copy of this object using connection.
     * It creates a new object filling in the simple attributes.
     * It then fills all the association collections and sets the
     * related objects to isNew=true.
     *
     * @param con the database connection to read associated objects.
     */
    public UnitStatistics copy(Connection con) throws TorqueException
    {
        return copy(true, con);
    }

    /**
     * Makes a copy of this object.
     * It creates a new object filling in the simple attributes.
     * If the parameter deepcopy is true, it then fills all the
     * association collections and sets the related objects to
     * isNew=true.
     *
     * @param deepcopy whether to copy the associated objects.
     */
    public UnitStatistics copy(boolean deepcopy) throws TorqueException
    {
        return copyInto(new UnitStatistics(), deepcopy);
    }

    /**
     * Makes a copy of this object using connection.
     * It creates a new object filling in the simple attributes.
     * If the parameter deepcopy is true, it then fills all the
     * association collections and sets the related objects to
     * isNew=true.
     *
     * @param deepcopy whether to copy the associated objects.
     * @param con the database connection to read associated objects.
     */
    public UnitStatistics copy(boolean deepcopy, Connection con) throws TorqueException
    {
        return copyInto(new UnitStatistics(), deepcopy, con);
    }
  
    /**
     * Fills the copyObj with the contents of this object.
     * The associated objects are also copied and treated as new objects.
     *
     * @param copyObj the object to fill.
     */
    protected UnitStatistics copyInto(UnitStatistics copyObj) throws TorqueException
    {
        return copyInto(copyObj, true);
    }

  
    /**
     * Fills the copyObj with the contents of this object using connection.
     * The associated objects are also copied and treated as new objects.
     *
     * @param copyObj the object to fill.
     * @param con the database connection to read associated objects.
     */
    protected UnitStatistics copyInto(UnitStatistics copyObj, Connection con) throws TorqueException
    {
        return copyInto(copyObj, true, con);
    }
  
    /**
     * Fills the copyObj with the contents of this object.
     * If deepcopy is true, The associated objects are also copied
     * and treated as new objects.
     *
     * @param copyObj the object to fill.
     * @param deepcopy whether the associated objects should be copied.
     */
    protected UnitStatistics copyInto(UnitStatistics copyObj, boolean deepcopy) throws TorqueException
    {
        copyObj.setID(iD);
        copyObj.setReportId(reportId);
        copyObj.setUnitNumber(unitNumber);

        copyObj.setID( 0);

        if (deepcopy)
        {


        List<UnitStatisticsData> vUnitStatisticsDatas = getUnitStatisticsDatas();
        if (vUnitStatisticsDatas != null)
        {
            for (int i = 0; i < vUnitStatisticsDatas.size(); i++)
            {
                UnitStatisticsData obj =  vUnitStatisticsDatas.get(i);
                copyObj.addUnitStatisticsData(obj.copy());
            }
        }
        else
        {
            copyObj.collUnitStatisticsDatas = null;
        }


        List<UnitStatisticsSkillData> vUnitStatisticsSkillDatas = getUnitStatisticsSkillDatas();
        if (vUnitStatisticsSkillDatas != null)
        {
            for (int i = 0; i < vUnitStatisticsSkillDatas.size(); i++)
            {
                UnitStatisticsSkillData obj =  vUnitStatisticsSkillDatas.get(i);
                copyObj.addUnitStatisticsSkillData(obj.copy());
            }
        }
        else
        {
            copyObj.collUnitStatisticsSkillDatas = null;
        }


        List<UnitStatisticsItemData> vUnitStatisticsItemDatas = getUnitStatisticsItemDatas();
        if (vUnitStatisticsItemDatas != null)
        {
            for (int i = 0; i < vUnitStatisticsItemDatas.size(); i++)
            {
                UnitStatisticsItemData obj =  vUnitStatisticsItemDatas.get(i);
                copyObj.addUnitStatisticsItemData(obj.copy());
            }
        }
        else
        {
            copyObj.collUnitStatisticsItemDatas = null;
        }
        }
        return copyObj;
    }
        
    
    /**
     * Fills the copyObj with the contents of this object using connection.
     * If deepcopy is true, The associated objects are also copied
     * and treated as new objects.
     *
     * @param copyObj the object to fill.
     * @param deepcopy whether the associated objects should be copied.
     * @param con the database connection to read associated objects.
     */
    protected UnitStatistics copyInto(UnitStatistics copyObj, boolean deepcopy, Connection con) throws TorqueException
    {
        copyObj.setID(iD);
        copyObj.setReportId(reportId);
        copyObj.setUnitNumber(unitNumber);

        copyObj.setID( 0);

        if (deepcopy)
        {


        List<UnitStatisticsData> vUnitStatisticsDatas = getUnitStatisticsDatas(con);
        if (vUnitStatisticsDatas != null)
        {
            for (int i = 0; i < vUnitStatisticsDatas.size(); i++)
            {
                UnitStatisticsData obj =  vUnitStatisticsDatas.get(i);
                copyObj.addUnitStatisticsData(obj.copy(con), con);
            }
        }
        else
        {
            copyObj.collUnitStatisticsDatas = null;
        }


        List<UnitStatisticsSkillData> vUnitStatisticsSkillDatas = getUnitStatisticsSkillDatas(con);
        if (vUnitStatisticsSkillDatas != null)
        {
            for (int i = 0; i < vUnitStatisticsSkillDatas.size(); i++)
            {
                UnitStatisticsSkillData obj =  vUnitStatisticsSkillDatas.get(i);
                copyObj.addUnitStatisticsSkillData(obj.copy(con), con);
            }
        }
        else
        {
            copyObj.collUnitStatisticsSkillDatas = null;
        }


        List<UnitStatisticsItemData> vUnitStatisticsItemDatas = getUnitStatisticsItemDatas(con);
        if (vUnitStatisticsItemDatas != null)
        {
            for (int i = 0; i < vUnitStatisticsItemDatas.size(); i++)
            {
                UnitStatisticsItemData obj =  vUnitStatisticsItemDatas.get(i);
                copyObj.addUnitStatisticsItemData(obj.copy(con), con);
            }
        }
        else
        {
            copyObj.collUnitStatisticsItemDatas = null;
        }
        }
        return copyObj;
    }
    
    

    /**
     * returns a peer instance associated with this om.  Since Peer classes
     * are not to have any instance attributes, this method returns the
     * same instance for all member of this class. The method could therefore
     * be static, but this would prevent one from overriding the behavior.
     */
    public UnitStatisticsPeer getPeer()
    {
        return peer;
    }

    /**
     * Retrieves the TableMap object related to this Table data without
     * compiler warnings of using getPeer().getTableMap().
     *
     * @return The associated TableMap object.
     */
    public TableMap getTableMap() throws TorqueException
    {
        return UnitStatisticsPeer.getTableMap();
    }


    public String toString()
    {
        StringBuffer str = new StringBuffer();
        str.append("UnitStatistics:\n");
        str.append("ID = ")
           .append(getID())
           .append("\n");
        str.append("ReportId = ")
           .append(getReportId())
           .append("\n");
        str.append("UnitNumber = ")
           .append(getUnitNumber())
           .append("\n");
        return(str.toString());
    }
}
